MicroForum/Controllers/ForumController.cs
using MicroForum.Data;
using MicroForum.Models;
using Microsoft.AspNetCore.Mvc;
using MicroForum.Models.ForumModels;
using MicroForum.Models.PostModels;
using Microsoft.Extensions.Options;

namespace MicroForum.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum _forumService;
        private readonly IPost _postService;

        public ForumController(IForum forumService, IPost postService)
        {
            _forumService = forumService;
            _postService = postService;
        }

        public IActionResult Index()
        {
            var forums = _forumService.GetAll().Select(forum => new ForumListingModel
            {
                Id = forum.Id, Description = forum.Description, Name = forum.Name
            });

            var model = new ForumIndexModel
            {
                ForumList = forums
            };

            return View(model);
        }

        public IActionResult Topic(int id, string searchQuery)
        {
            var forum = _forumService.GetById(id);
            var posts = new List<Post>();

            posts = _postService.GetFiltered(forum, searchQuery).ToList();


            // posts = forum.Posts;


            var postListings = posts.Select(post => new PostListingModel
            {
                Id = post.Id,
                AuthorId = post.User.Id,
                AuthorRating = post.User.Rating,
                AuthorName = post.User.UserName,
                Title = post.Title,
                CreatedDate = post.CreatedDate,
                RepliesCount = post.Replies?.Count(),
                Forum = BuildForumListing(post)
            });

            var model = new ForumTopicModel
            {
                Posts = postListings,
                Forum = BuildForumListing(forum)
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Search(int id, string searchQuery)
        {
            return RedirectToAction("Topic", new { id, searchQuery });
        }

        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;

            return BuildForumListing(forum);
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.Id,
                Name = forum.Name,
                Description = forum.Description,
                ForumImageUrl = forum.ImageUrl
            };
        }
    }
}

MicroForum/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MicroForum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MicroForum.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MicroForum</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="Index">Forums</a>
                    </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button"></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a a asp-controller="Profile" asp-action="Detail">My Profile</a>
                                </li>
                                @if (User.IsInRole("Admin"))
                                {
                                    <li>
                                        <a a asp-controller="Forum" asp-action="Create">Create forum</a>
                                    </li>
                                    <li>
                                        <a a asp-controller="Profile" asp-action="Index">View users</a>
                                    </li>
                                }
                            </ul>
                        </li>
                    }
                    </ul>
                        @if (!SignInManager.IsSignedIn(User))
                        {
                            <ul class="dropdown-menu">
                                <li>
                                    <a a asp-controller="Account" asp-action="Login">Sign in</a>
                                </li>
                                <li>
                                    <a a asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            </ul>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <form asp-controller="Account" asp-action="Logout" method="post" id="logoutForm">
                                <ul class="dropdown-menu">
                                    <li>Hello, @UserManager.GetUserName(User)</li>
                                    <li>
                                        <a a asp-controller="Account" asp-action="Logout">Logout</a>
                                    </li>
                                </ul>
                            </form>
                        }
                    

               
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - MicroForum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>